FROM centos:7.9.2009

RUN yum update -y && \
    yum install -y python3

FROM python:3.9
RUN pip install pandas
RUN pip install geopandas

RUN mkdir /app
WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip3 install --user -r /app/requirements.txt

COPY /src/app.py /app
COPY /src/worker.py /app
COPY /src/jobs.py /app

ENTRYPOINT ["python3"]
CMD ["worker.py"]

ENV LC_CTYPE=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8  
ENV LANGUAGE=en_US.UTF-8
ENV LANG=en_US.UTF-8  